// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return (function() {
      $.jImageSwipe({
        box: '#photoList',
        slide: 'ul',
        slideSize: 268,
        callback: function() {}
      });
      $(document).on('click', '#right', function(event) {
        return $.jImageSwipe.right();
      });
      return $(document).on('click', '#left', function(event) {
        return $.jImageSwipe.left();
      });
    })();
  });

}).call(this);
