// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return (function() {
      return $.jImageSwipe({
        box: "#photoList",
        slide: 'ul',
        slideSize: 268,
        callback: function() {}
      });
    })();
  });

}).call(this);
